name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Instalar pytest para rodar testes (se houver)
        pip install pytest

    - name: Rodar validação da Base de Conhecimento
      run: |
        python valida_output.py

    - name: Rodar testes automatizados (Opcional)
      run: |
        # Se você tiver testes em uma pasta 'tests/', eles serão executados aqui.
        # Ex: pytest tests/
        echo "Nenhum teste automatizado definido ainda. Crie arquivos em 'tests/' para ativá-los."

    - name: Construir e Empurrar Imagem Docker (Opcional)
      # Esta etapa seria usada para construir sua imagem Docker e enviá-la para um registro (ex: Docker Hub, GHCR)
      # Necessitaria de credenciais e configuração de registro.
      # Ex: docker build -t seu-usuario/seu-repo:latest .
      # Ex: docker push seu-usuario/seu-repo:latest
      run: echo "Etapa de construção e push da imagem Docker (desabilitada por padrão)."

    - name: Deploy para Plataforma de Nuvem (Opcional)
      # Esta etapa seria usada para fazer o deploy da sua aplicação para um serviço como Render, Heroku, AWS, etc.
      # A configuração dependerá da plataforma escolhida.
      run: echo "Etapa de deploy para produção (desabilitada por padrão)."